--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "Please report bugs in your org's Linear team"
    name: Bug
    url: "https://linear.app/kienleholdings/"
  - 
    about: "Please file feature requests in your org's Notion space"
    name: Feature Request
    url: "https://www.notion.so/kienleholdings/Orgs-0f25ac20f3ae4543b260292152cf4236"
