version: '3.8'

services:
  open-source: # This can be named anything as long as it's the same in devcontainer.json
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity # This allows VSCode to start the container without being forced to run any apps
    container_name: open-source
    volumes:
      - ..:/workspace:cached
